config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get 'sign_in', to: 'auth#new'
    delete 'sign_out', to: 'auth#destroy'

    resources :bulletins do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      resources :bulletins, only: :index do
        member do
          patch 'reject'
          patch 'publish'
          patch 'archive'
        end
      end
      resources :categories
    end

    resource :profile, only: :show
  end
end

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |type, msg|
      div class="alert alert-dismissible #{flash_class(type.to_s)}"
        = msg
        button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.bg-dark.bg-gradient.px-3.mb-3.rounded-bottom.border-bottom.border-warning.border-1.sticky-top
  .container-fluid
    = link_to t('board'), root_path, class: 'navbar-brand text-warning'

  .navbar-nav.me-auto.mb-2.mb-lg-0

  .nav-item
    = link_to t('bulletins'), bulletins_path, class: 'nav-link text-secondary'

  - if policy(:admin).admin?

    .nav-item.dropdown
      a#navbarDropdown.nav-link.dropdown-toggle.text-secondary[href='#' role='button' data-bs-toggle='dropdown' aria-expanded='false']
        = t('administration')

      .dropdown-menu-end.bg-dark.bg-gradient.dropdown-menu[aria-labelledby="navbarDropdown"]
          li
            = link_to t('bulletins'), admin_bulletins_path, class: 'dropdown-item text-secondary'
          li
            = link_to t('categories'), admin_categories_path, class: 'dropdown-item text-secondary'

  .nav-item.dropdown
    a#navbarDropdown.nav-link.dropdown-toggle.text-secondary[href='#' role='button' data-bs-toggle='dropdown' aria-expanded='false']
      - if signed_in? && current_user.avatar_url.present?
        = current_user.name
        = image_tag current_user.avatar_url, size: '32x32', class: 'rounded-circle ms-2'
      - else
        i.fa-solid.fa-house-user.text-light

    .dropdown-menu-end.bg-dark.bg-gradient.dropdown-menu[aria-labelledby="navbarDropdown"]
      - if signed_in?
        li
          = link_to t('profile'), profile_path, class: 'dropdown-item text-secondary'
        li
          = link_to t('sign_out'), sign_out_path, method: :delete, class: 'dropdown-item text-secondary'
      - else
        li
          = link_to t('sign_in'), sign_in_path, class: 'dropdown-item text-secondary'