config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get 'sign_in', to: 'auth#new'
    delete 'sign_out', to: 'auth#destroy'

    resources :bulletins do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      resources :bulletins, only: :index do
        member do
          patch 'reject'
          patch 'publish'
          patch 'archive'
        end
      end
      resources :categories
    end

    resource :profile, only: :show
  end
end

app/controllers/web/profiles_controller.rb
# frozen_string_literal: true

class Web::ProfilesController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    get_query('bulletin')
    @tabs = %w[all under_moderation draft published rejected archived]
    @active_tab = params[:tab] || 'all'

    @q = current_user.bulletins.ransack(@query)
    @bulletins = @q.result.order(created_at: :desc).page(params[:page]).per(15).send(@active_tab)
  end
end

app/views/web/profiles/_list.html.slim
.row
  .col-4
    = bulletin.title
  .col-2.text-secondary
    = bulletin.aasm.human_state
  .col-6
    =< link_to t('show'), bulletin_path(bulletin)
    =< link_to t('edit'), edit_bulletin_path(bulletin)
    - if bulletin.may_moderate?
      =< link_to t('to_moderate'), to_moderate_bulletin_path(bulletin), method: :patch, data: { confirm: t('confirm_to_moderate') }
    - if bulletin.may_archive?
      =< link_to t('to_archive'), archive_bulletin_path(bulletin), method: :patch, data: { confirm: t('confirm_to_archive') }
hr

app/views/web/profiles/show.html.slim
.d-flex.justify-content-between
  h1
    = t('my_bulletins')

  = link_to t('new_bulletin'), new_bulletin_path, class: 'btn btn-primary btn-lg'
.d-flex.justify-content-center
  = search_form_for @q, url: profile_path, class: 'form w-50' do |f|
    .input-group
      = f.search_field :title_cont, class: 'form-control form-control-lg border-0', placeholder: t('search')
      - if @query
        = link_to profile_path(clear: 'this') do
          button type="button" class="btn my-1 bg-transparent" style="margin-left: -40px; z-index: 100;"
            i class="fa fa-times align-middle"
      = f.button :button, class: 'btn btn-light bg-white border-start-0 input-group-append' do
        i.fa-solid.fa-magnifying-glass

nav.my-3
  .nav.nav-tabs.my-3 id="nav-tab" role="tablist"
    - @tabs.each do |tab_id|
      = link_to t(tab_id.to_s), profile_path(tab: tab_id.to_s),
      { 'class' => "nav-link #{'active' if params[:tab] == tab_id}", 'id' => tab_id.to_s, 'data-bs-target' => "#nav-#{tab_id}",
      'type' => 'button', 'role' => 'tab', 'aria-controls' => "nav-#{tab_id}", 'aria-selected' => @active_tab == tab_id ? 'true' : 'false' }

  .tab-content id="nav-tabContent"

    .row.text-info
      .col-4
        = t('title')
      .col-2
        = t('status')
      .col-6
        = t('actions')
    hr.text-info

    div class="tab-pane show active fade" id="nav-#{@active_tab}" role="tabpanel" aria-labelledby="nav-#{@active_tab}-tab"
      = paginate @bulletins, params: { tab: @active_tab }, theme: 'bootstrap-5', pagination_class: 'pagination-sm flex-wrap justify-content-end', nav_class: 'd-inline-block'
      - @bulletins.each do |bulletin|
        = render partial: 'web/profiles/list', locals: { bulletin: bulletin }