config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get 'sign_in', to: 'auth#new'
    delete 'sign_out', to: 'auth#destroy'

    resources :bulletins do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      resources :bulletins, only: :index do
        member do
          patch 'reject'
          patch 'publish'
          patch 'archive'
        end
      end
      resources :categories
    end

    resource :profile, only: :show
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true
  has_many :bulletins, dependent: :delete_all
end

app/controllers/web/admin/categories_controller.rb
# frozen_string_literal: true

class Web::Admin::CategoriesController < Web::Admin::ApplicationController
  def index
    @categories = Category.page(params[:page]).per(15)
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_category_path(@category), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to admin_categories_path, notice: t('.success')
    else
      redirect_to admin_categories_path, alert: t('.fail')
    end
  end

  def category_params
    params.require(:category).permit([:name])
  end
end

app/views/web/admin/categories/_form.html.slim
= simple_form_for [:admin, category] do |f|
  = f.error_notification
  = f.input :name
  = f.button :submit, class: 'btn btn-outline-warning my-2'

app/views/web/admin/categories/edit.html.slim
h1.my-3
  = t('edit_category')
= render partial: 'form', locals: { category: @category }
= link_to t('categories'), admin_categories_path, class: 'btn btn-outline-primary'

app/views/web/admin/categories/index.html.slim
.d-flex.justify-content-between
  h1.text-info
    = t('categories')
  span
    = link_to t('new_category'), new_admin_category_path, class: 'btn btn-outline-warning'

hr.text-info
.list-group
  = paginate @categories, theme: 'bootstrap-5', pagination_class: 'pagination-sm flex-wrap justify-content-end', nav_class: 'd-inline-block'
  - @categories.each do |category|
    .list-group-item.list-group-item-action.list-group-item-primary
      .d-flex.justify-content-between
        = link_to admin_category_path(category) do
          = category.name
        div
          = link_to t('delete'), admin_category_path(category), method: :delete, data: { confirm: 'are_you_sure' }
          =< link_to t('edit'), edit_admin_category_path(category)

app/views/web/admin/categories/new.html.slim
h1.my-3
  = t('new_category')
= render partial: 'form', locals: { category: @category }
= link_to t('back'), admin_categories_path, class: 'my-3 btn btn-primary'

app/views/web/admin/categories/show.html.slim
h1.m-3
  = @category.name
span
  = link_to t('categories'), admin_categories_path, class: 'btn btn-outline-primary'
  =<  link_to t('delete'), admin_category_path(@category), method: :delete, data: { confirm: 'are_you_sure' }, class: 'btn btn-outline-danger'
  =< link_to t('edit'), edit_admin_category_path(@category), class: 'btn btn-outline-warning'