config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get 'sign_in', to: 'auth#new'
    delete 'sign_out', to: 'auth#destroy'

    resources :bulletins do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      resources :bulletins, only: :index do
        member do
          patch 'reject'
          patch 'publish'
          patch 'archive'
        end
      end
      resources :categories
    end

    resource :profile, only: :show
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :category
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image, attached: true, content_type: %i[png jpg jpeg], size: { less_than: 5.megabytes, message: :too_large }

  aasm column: :state, whiny_transitions: false do
    state :draft, initial: true
    state :under_moderation
    state :published
    state :rejected
    state :archived

    event :moderate do
      transitions from: %i[draft rejected], to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published rejected], to: :archived
    end
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

class Web::Admin::BulletinsController < Web::Admin::ApplicationController
  def index
    get_query('bulletin')
    @tabs = %w[all under_moderation draft published rejected archived]
    @active_tab = params[:tab] || 'all'

    @q = Bulletin.ransack(@query)
    @bulletins = @q.result.order(created_at: :desc).includes(:user).page(params[:page]).send(@active_tab)
  end

  def reject
    bulletin = Bulletin.find(params[:id])
    if bulletin.may_reject?
      bulletin.reject!
      redirect_to admin_bulletins_path, notice: t('.success')
    else
      flash[:alert] = t('.fail')
      redirect_to bulletin_path(bulletin)
    end
  end

  def publish
    bulletin = Bulletin.find(params[:id])
    if bulletin.may_publish?
      bulletin.publish!
      redirect_to admin_bulletins_path, notice: t('.success')
    else
      flash[:alert] = t('.fail')
      redirect_to bulletin_path(bulletin)
    end
  end

  def archive
    bulletin = Bulletin.find(params[:id])
    if bulletin.may_archive?
      bulletin.archive!
      redirect_to admin_bulletins_path, notice: t('.success')
    else
      flash[:alert] = t('.fail')
      redirect_to bulletin_path(bulletin)
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

class Web::BulletinsController < Web::ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy to_moderate archive]

  def index
    @q = Bulletin.published.ransack(params[:q])
    @bulletins = @q.result.order(created_at: :desc).includes(:category).page(params[:page])
  end

  def show
    @bulletin = find_bulletin
    authorize @bulletin
  end

  def new
    @bulletin = Bulletin.new
  end

  def create
    @bulletin = current_user.bulletins.new(bulletin_params)
    if @bulletin.save
      redirect_to bulletin_path(@bulletin), notice: t('.success')
    else
      render :new
    end
  end

  def edit
    @bulletin = find_bulletin
    authorize @bulletin
  end

  def update
    @bulletin = find_bulletin
    authorize @bulletin
    if @bulletin.update(bulletin_params)
      redirect_to bulletin_path(@bulletin), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @bulletin = find_bulletin
    authorize @bulletin
    if @bulletin.destroy
      redirect_to profile_path, notice: t('.success')
    else
      redirect_to profile_path, alert: t('.fail')
    end
  end

  def to_moderate
    @bulletin = find_bulletin
    authorize @bulletin
    if @bulletin.may_moderate?
      @bulletin.moderate!
      redirect_to profile_path, notice: t('.success')
    else
      flash[:alert] = t('.fail')
      redirect_to bulletin_path(@bulletin)
    end
  end

  def archive
    @bulletin = find_bulletin
    authorize @bulletin
    if @bulletin.may_archive?
      @bulletin.archive!
      redirect_to profile_path, notice: t('.success')
    else
      flash[:alert] = t('.fail')
      redirect_to bulletin_path(@bulletin)
    end
  end

  private

  def bulletin_params
    params.require(:bulletin).permit(%i[category_id title description image])
  end

  def find_bulletin
    Bulletin.find(params[:id])
  end
end

app/views/web/admin/bulletins/_list.html.slim
.row
  .col-4
    = bulletin.title
  .col-2.text-secondary
    = bulletin.aasm.human_state
  .col-6
    =< link_to t('show'), bulletin_path(bulletin)
    - if bulletin.may_publish?
      =< link_to t('publish'), publish_admin_bulletin_path(bulletin), method: :patch, data: { confirm: t('confirm_to_publish') }
    - if bulletin.may_reject?
      =< link_to t('reject'), reject_admin_bulletin_path(bulletin), method: :patch, data: { confirm: t('confirm_to_reject') }
    - if bulletin.may_archive?
      =< link_to t('to_archive'), archive_admin_bulletin_path(bulletin), method: :patch, data: { confirm: t('confirm_to_archive') }
hr

app/views/web/admin/bulletins/index.html.slim
h1
  = t('bulletins')

.d-flex.justify-content-center
  = search_form_for @q, url: admin_bulletins_path, class: 'form w-50' do |f|
    .input-group
      = f.search_field :title_cont, class: 'form-control form-control-lg border-0', placeholder: t('search')
      - if @query
        = link_to admin_bulletins_path(clear: 'this') do
          button type="button" class="btn my-1 bg-transparent" style="margin-left: -40px; z-index: 100;"
            i class="fa-regular fa-circle-xmark align-middle"
      = f.button :button, class: 'btn btn-light bg-white border-start-0 input-group-append' do
        i.fa-solid.fa-magnifying-glass

nav.my-3
  .nav.nav-tabs.my-3 id="nav-tab" role="tablist"
    - @tabs.each do |tab_id|
      = link_to t(tab_id.to_s), admin_bulletins_path(tab: tab_id.to_s),
      { 'class' => "nav-link #{'active' if params[:tab] == tab_id}", 'id' => tab_id.to_s, 'data-bs-target' => "#nav-#{tab_id}",
      'type' => 'button', 'role' => 'tab', 'aria-controls' => "nav-#{tab_id}", 'aria-selected' => @active_tab == tab_id ? 'true' : 'false' }

  .tab-content id="nav-tabContent"

    .row.text-info
      .col-4
        = t('title')
      .col-2
        = t('status')
      .col-6
        = t('actions')
    hr.text-info

    div class="tab-pane show active fade" id="nav-#{@active_tab}" role="tabpanel" aria-labelledby="nav-#{@active_tab}-tab"
      = paginate @bulletins, params: { tab: @active_tab }, theme: 'bootstrap-5', pagination_class: 'pagination-sm flex-wrap justify-content-end', nav_class: 'd-inline-block'
      - @bulletins.each do |bulletin|
        = render partial: 'web/admin/bulletins/list', locals: { bulletin: bulletin }